Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2021-12, with the labels that each got.

#62 Disable/enable for all clusters feature
  compiled-lang/en.json
  src/Components/Modals/DisableRule.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Messages.js
  src/Services/Acks.js
  src/Store/index.js
  src/Utilities/Api.js
Labels: enhancement

#63 Added coming soon error message to the Clusters pages in OCP Advisor
  compiled-lang/en.json
  src/App.scss
  src/Components/MessageState/EmptyStates.js
  src/Messages.js
  src/Routes.js
Labels: enhancement

#67 Add systems (clusters) page
  cypress/fixtures/ClustersListTable/data.json
  package-lock.json
  package.json
  src/AppConstants.js
  src/Components/ClustersList/index.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/ClustersListTable/index.js
  src/Components/Common/Tables.js
  src/Components/RecsListTable/RecsListTable.js
  src/Routes.js
  src/Services/Filters.js
  src/Services/SmartProxy.js
Labels: enhancement

#68 Added expand/collapse all button with icon to the Primary toolbar
  src/Components/RecsListTable/RecsListTable.js
Labels: enhancement

#71 Recommendations list page: minor enhancements
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.scss
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Services/Filters.js
Labels: bug

#70 Single recommendation page improvements
  cypress/fixtures/AffectedClustersTable/data.json
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Services/Filters.js
Labels: bug, enhancement

#73 [Recommendations list table] Add the Category column
  src/AppConstants.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/Labels/CategoryLabel.js
  src/Components/Labels/RuleLabels.js
  src/Components/Recommendation/Recommendation.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Services/Filters.js
Labels: enhancement

#74 When authenticating user, render spinner instead of the lock icon
  src/App.js
Labels: enhancement

#75 Improve page document titles; affected clusters table enhancements
  cypress/fixtures/AffectedClustersTable/data.json
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClustersList/index.js
  src/Components/Recommendation/index.js
  src/Components/RecsList/index.js
Labels: enhancement

#76 Hide disabled rules for single cluster page
  src/AppConstants.js
  src/Components/Cluster/index.js
  src/Components/ClusterRules/ClusterRules.js
  src/Services/SmartProxy.js
Labels: enhancement

#66 Single recommendation page: disable/enable recommendation for a group of clusters feature
  compiled-lang/en.json
  cypress/fixtures/AffectedClustersTable/data.json
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Modals/DisableRule.js
  src/Components/Modals/ViewHostAcks.js
  src/Components/Recommendation/Recommendation.js
  src/Components/Recommendation/index.js
  src/Messages.js
  src/Services/Acks.js
  src/Utilities/Api.js
  src/Utilities/Loaders.js
Labels: enhancement
