Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2022-04, with the labels that each got.

#211 refactor(Recommendations list table): rearrange component hierarchy and add ouiaSafe support
  src/Components/RecsListTable/RecsListTable.js
Labels: enhancement

#212 Release to candidate (prod-beta)
  CHANGELOG.md
  cypress/utils/components.js
  package-lock.json
  package.json
  src/App.js
  src/AppEntry.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Modals/DisableRule.spec.ct.js
  src/Components/RecsListTable/RecsListTable.js
  src/Services/Filters.js
Labels: release/sync-up

#213 Release to production (prod-stable)
  CHANGELOG.md
  cypress/utils/components.js
  package-lock.json
  package.json
  src/App.js
  src/AppEntry.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Modals/DisableRule.spec.ct.js
  src/Components/RecsListTable/RecsListTable.js
  src/Services/Filters.js
Labels: release/sync-up

#227 Import RuleDetails from @redhat-cloud-services/frontend-components-advisor-components
  ARCHITECTURE.md
  package-lock.json
  package.json
  src/Components/Recommendation/Recommendation.js
  src/Components/Recommendation/RuleDetails.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Components/RuleDetailsLocal/RuleDetails.js
  src/Components/RuleDetailsLocal/RuleRating.js
  src/Components/RuleDetailsLocal/_RuleDetails.scss
  src/Components/RuleDetailsLocal/_RuleRating.scss
  src/Components/RuleDetailsLocal/index.js
  src/Utilities/intlHelper.js
Labels: enhancement

#234 Refactor test
  cypress/support/commands.js
  cypress/utils/components.js
  cypress/utils/table.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#228 Move cypress fixture data files to api folder
  cypress/fixtures/Cluster/report.json
  cypress/fixtures/ClusterRules/data.json
  cypress/fixtures/api/insights-results-aggregator/v2/ack/external.rules.rule|ERROR_KEY.json
  cypress/fixtures/api/insights-results-aggregator/v2/cluster/dcb95bbf-8673-4f3a-a63c-12d4a530aa6f/reports-disabled-false.json
  cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail/report.json
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#236 Pagination utils
  cypress/utils/pagination.js
  cypress/utils/table.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
Labels: tests

#237 Rename table component to root and improve is rendered tests
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests
