Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2022-08, with the labels that each got.

#380 Release to candidate (prod-beta)
  CHANGELOG.md
  README.md
  cypress.config.js
  cypress.json
  cypress/fixtures/api/insights-results-aggregator/v2/cluster/dcb95bbf-8673-4f3a-a63c-12d4a530aa6f/reports-disabled-false.json
  cypress/plugins/index.js
  cypress/support/component-index.html
  cypress/support/component.js
  package-lock.json
  package.json
  src/AppConstants.js
  src/Components/AffectedClustersTable/AffectedClustersTable.cy.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/Breadcrumbs/Breadcrumbs.cy.js
  src/Components/Cluster/Cluster.cy.js
  src/Components/ClusterHeader/ClusterHeader.cy.js
  src/Components/ClusterRules/ClusterRules.cy.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClustersListTable/ClustersListTable.cy.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/Modals/DisableRule.cy.js
  src/Components/Recommendation/Recommendation.cy.js
  src/Components/RecsListTable/RecsListTable.cy.js
  src/Components/RecsListTable/RecsListTable.js
Labels: release/sync-up

#373 Recommendation page tests
  src/Components/Modals/ViewHostAcks.js
  src/Components/Modals/ViewHostsAcks.cy.js
  src/Components/Recommendation/Recommendation.cy.js
Labels: tests

#382 feat(ClustersList): new tests for url params
  cypress/utils/components.js
  cypress/utils/filters.js
  src/Components/ClustersListTable/ClustersListTable.cy.js
  src/Components/RecsListTable/RecsListTable.cy.js
Labels: enhancement

#389 fix(Tables): reduce re-renders; fix the incorrect data-ouia-safe attribute
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/RecsListTable/RecsListTable.js
Labels: bug
