Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2022-06, with the labels that each got.

#303 Avoid force: true in cypress tests
  cypress/utils/filters.js
  cypress/views/filterableTable.js
  package-lock.json
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: bug, tests

#309 Fix wrong placement of "Expand all" button in tables
  cypress/utils/components.js
  cypress/utils/table.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: bug

#315 fix(Cluster reports): fix infinite table re-render when there are no rules
  src/Components/ClusterRules/ClusterRules.js
Labels: bug

#310 [CCXDEV-8325] Adding OUIA IDs
  src/Components/Modals/ViewHostAcks.js
  src/Components/Recommendation/Recommendation.js
Labels: tests

#311 [CCXDEV-7133] Bulk selector tests improve
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
Labels: tests

#312 [CCXDEV-7133] Improve default tests
  src/Components/ClusterRules/ClusterRules.spec.ct.js
Labels: tests

#316 fix(Recommendation clusters): Fix always checked checkbox in the disable rule modal
  src/Components/AffectedClustersTable/AffectedClustersTable.js
Labels: bug

#319 Release to candidate (prod-beta)
  CHANGELOG.md
  package-lock.json
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Modals/ViewHostAcks.js
  src/Components/Recommendation/Recommendation.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: release/sync-up

#320 Release to production (prod-stable)
  CHANGELOG.md
  compiled-lang/en.json
  cypress/utils/components.js
  cypress/utils/filters.js
  cypress/utils/table.js
  cypress/views/filterableTable.js
  package-lock.json
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Cluster/Cluster.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/ClusterHeader/ClusterHeader.js
  src/Components/ClusterHeader/ClusterHeader.spec.ct.js
  src/Components/ClusterHeader/index.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Loading/Loading.js
  src/Components/MessageState/EmptyStates.js
  src/Components/MessageState/MessageState.js
  src/Components/Modals/ViewHostAcks.js
  src/Components/Recommendation/Recommendation.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Messages.js
  src/Services/SmartProxy.js
Labels: release/sync-up

#326 refactor(Page headers): use PF Title instead FEC PageHeaderTitle
  src/Components/ClustersList/index.js
  src/Components/RecsList/index.js
Labels: tests

#325 refactor(Empty states): set proper OUIA attributes to empty state containers
  cypress/utils/table.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/MessageState/MessageState.js
Labels: tests

#327 test(Pagination check): nest checkRowCounts within "then" callback
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#328 Share code for filtering tests
  cypress/utils/table.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#329 Disabled label
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#313 [CCXDEV-6982] Check category labels in recommendation page
  src/Components/Recommendation/Recommendation.spec.ct.js
Labels: tests

#300 refactor(ReportDetails): replaced the component with the library one
  ARCHITECTURE.md
  config/dev.webpack.config.js
  package-lock.json
  package.json
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ReportDetails/ReportDetails.js
Labels: enhancement
