Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2022-07, with the labels that each got.

#324 Function for sorting tests
  cypress/utils/table.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#340 feat(Single recommendation page): add Impacted column
  compiled-lang/en.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
  package-lock.json
  src/AppConstants.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Messages.js
Labels: enhancement

#330 Improve single recommendation tests
  src/Components/Recommendation/Recommendation.spec.ct.js
Labels: tests

#344 [CCXDEV-8358] Add expand/collapse all rows test to RecsListTable
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#356 fix(Recommendation page): fix missing thank you message on vote click
  compiled-lang/en.json
  src/Messages.js
Labels: bug

#355 Release to candidate (prod-beta)
  ARCHITECTURE.md
  CHANGELOG.md
  compiled-lang/en.json
  config/dev.webpack.config.js
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
  cypress/utils/table.js
  package-lock.json
  package.json
  src/AppConstants.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersList/index.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/MessageState/MessageState.js
  src/Components/Recommendation/Recommendation.js
  src/Components/Recommendation/Recommendation.spec.ct.js
  src/Components/RecsList/index.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Components/ReportDetails/ReportDetails.js
  src/Messages.js
Labels: release/sync-up

#357 Release to production (prod-stable)
  ARCHITECTURE.md
  CHANGELOG.md
  compiled-lang/en.json
  config/dev.webpack.config.js
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
  cypress/utils/table.js
  package-lock.json
  package.json
  src/AppConstants.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersList/index.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/MessageState/MessageState.js
  src/Components/Recommendation/Recommendation.js
  src/Components/Recommendation/Recommendation.spec.ct.js
  src/Components/RecsList/index.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Components/ReportDetails/ReportDetails.js
  src/Messages.js
Labels: release/sync-up

#359 refactor(Recommendations list): Map sorting search parameters from column names
  src/AppConstants.js
  src/Components/RecsListTable/RecsListTable.cy.js
  src/Components/RecsListTable/RecsListTable.js
Labels: enhancement

#365 OUIA safe tags for tables
  README.md
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/ClusterRules/ClusterRules.cy.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/RecsListTable/RecsListTable.js
Labels: enhancement

#366 feat(ClusterRules): Add impacted to single Cluster page
  cypress/fixtures/api/insights-results-aggregator/v2/cluster/dcb95bbf-8673-4f3a-a63c-12d4a530aa6f/reports-disabled-false.json
  src/AppConstants.js
  src/Components/ClusterRules/ClusterRules.cy.js
  src/Components/ClusterRules/ClusterRules.js
Labels: enhancement
