Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2022-10, with the labels that each got.

#434 fix: Fix cypress test coverage
  coverage.sh
  cypress.config.js
  cypress/support/component.js
  cypress/support/index.js
  package.json
Labels: bug

#441 feat(GitHubActions): Add cypress yml config to run github actions
  .github/workflows/cypress.yml
  .travis.yml
Labels: enhancement

#445 chore: Allow minor and patch updates to deps
  package.json
Labels: dependencies
