Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2022-03, with the labels that each got.

#128 Cluster List added a check for the clusters that missing both clustername and external id
  src/Services/SmartProxy.js
Labels: bug

#134 Sync-up stage with stage-beta
  compiled-lang/en.json
  package-lock.json
  package.json
  src/AppConstants.js
  src/Components/Recommendation/RuleDetails.js
  src/Components/RuleDetailsLocal/RuleDetails.js
  src/Components/RuleDetailsLocal/RuleRating.js
  src/Components/RuleDetailsLocal/_RuleDetails.scss
  src/Components/RuleDetailsLocal/_RuleRating.scss
  src/Components/RuleDetailsLocal/index.js
  src/Messages.js
  src/Services/SmartProxy.js
Labels: release/sync-up

#133 Clusters list, recommendations list pages: solving the UI inconstistency
  src/Services/SmartProxy.js
Labels: bug

#135 Update README.md
  README.md
Labels: documentation

#136 feat: integrate semantic-release
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: enhancement

#168 fix(labels): rule details component: make labels compact
  src/Components/ClusterRules/ClusterRules.js
  src/Components/RuleDetailsLocal/RuleDetails.js
Labels: bug

#173 fix(ClusterRules): fix description chip category name
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
Labels: bug

#174 fix: keep original order of entities in all tables
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: bug

#182 Release to production (prod-stable)
  .babelrc
  .dependabot/config.yml
  .github/dependabot.yml
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  compiled-lang/en.json
  config/dev.webpack.config.js
  coverage.sh
  cypress/fixtures/AffectedClustersTable/data.json
  cypress/fixtures/ClustersListTable/data.json
  cypress/fixtures/RecsListTable/data.json
  cypress/fixtures/api/insights-results-aggregator/v2/ack/external.rules.rule|ERROR_KEY/report.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail/report.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/report.json
  cypress/plugins/index.js
  cypress/support/index.js
  cypress/utils/components.js
  cypress/utils/defaults.js
  cypress/utils/globals.js
  jest.config.js
  package-lock.json
  package.json
  src/AppConstants.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Cluster/Cluster.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/ClusterHeader/ClusterHeader.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Components/ReportDetails/ReportDetails.js
  src/Components/RuleDetailsLocal/RuleDetails.js
  src/Messages.js
  src/Services/SmartProxy.js
Labels: on hold, release/sync-up

#183 fix(RecsListTable): Reset filters button behavior update
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: enhancement

#187 fix(disable modal): bug with multiple selections
  src/Components/Modals/DisableRule.js
Labels: bug

#190 Release to candidate (prod-beta)
  CHANGELOG.md
  package-lock.json
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Cluster/index.js
  src/Components/ClustersList/index.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/Modals/DisableRule.js
  src/Components/Recommendation/index.js
  src/Components/RecsList/index.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: release/sync-up

#191 Release to production (prod-stable)
  CHANGELOG.md
  package-lock.json
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Cluster/index.js
  src/Components/ClustersList/index.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/Modals/DisableRule.js
  src/Components/Recommendation/index.js
  src/Components/RecsList/index.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: release/sync-up

#196 feat(Clusters list table): filters edition modifies search params
  src/AppConstants.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Common/Tables.js
Labels: enhancement

#197 Cluster reports table: refactor and fix the bug with inability to sort the table
  cypress/fixtures/ClusterRules/data.json
  src/AppConstants.js
  src/Components/Cluster/Cluster.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/Loading/Loading.js
Labels: bug, enhancement

#198 Release to candidate (prod-beta)
  CHANGELOG.md
  README.md
  compiled-lang/en.json
  cypress/fixtures/ClusterRules/data.json
  package-lock.json
  package.json
  src/App.scss
  src/AppConstants.js
  src/Components/Cluster/Cluster.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/ClusterHeader/ClusterHeader.js
  src/Components/ClusterHeader/ClusterHeader.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Common/Tables.js
  src/Components/Loading/Loading.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Messages.js
Labels: release/sync-up

#199 Release to production (prod-stable)
  CHANGELOG.md
  README.md
  compiled-lang/en.json
  cypress/fixtures/ClusterRules/data.json
  package-lock.json
  package.json
  src/App.scss
  src/AppConstants.js
  src/Components/Cluster/Cluster.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/ClusterHeader/ClusterHeader.js
  src/Components/ClusterHeader/ClusterHeader.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Common/Tables.js
  src/Components/Loading/Loading.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Messages.js
Labels: release/sync-up

#202 fix(AffectedClustersTable): set default sorting to last seen
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Services/Filters.js
Labels: enhancement
