Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2022-05, with the labels that each got.

#238 Last seen at
  cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
Labels: tests

#239 Pagination related tests for RecsListTable
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#242 Remove duplicated tests
  cypress/support/commands.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
Labels: tests

#240 Move importing PF CSS to cypress support
  cypress/support/index.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Breadcrumbs/Breadcrumbs.spec.ct.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/ClusterHeader/ClusterHeader.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Modals/DisableRule.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#241 Affected clusters tests improvement
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
Labels: tests

#250 RecsListTable tests improvement
  cypress/utils/components.js
  cypress/utils/filters.js
  cypress/utils/table.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#252 Improve Clusters list table tests
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
Labels: tests

#254 Get headers for testing tables from AppConstants file
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
Labels: tests

#256 Reduce the number of sort tests for ClusterRules first query parameter
  src/Components/ClusterRules/ClusterRules.spec.ct.js
Labels: tests

#251 fix(ClusterRules): Open rows memorization
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
Labels: enhancement

#260 refactor: use updateDocumentTitle to update page titles
  src/Components/Cluster/index.js
  src/Components/ClustersList/index.js
  src/Components/Recommendation/index.js
  src/Components/RecsList/index.js
Labels: enhancement

#261 fix(Cluster rules table): display table rows only when filtering is completed
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
Labels: bug

#255 Include filtering condition in filtersConf
  cypress/utils/filters.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
Labels: tests

#264 Update FEC config library to disable dot rule
  package-lock.json
  package.json
  src/Components/RecsListTable/RecsListTable.js
Labels: bug

#262 Minor improvements to tests
  cypress/utils/components.js
  cypress/utils/table.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#263 fix(RecsListTable): Fixing the category sorting
  cypress/fixtures/api/insights-results-aggregator/v2/rule.json
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: bug

#271 Release to candidate (prod-beta)
  .github/dependabot.yml
  .stylelintrc.json
  ARCHITECTURE.md
  CHANGELOG.md
  cypress/fixtures/Cluster/report.json
  cypress/fixtures/ClusterRules/data.json
  cypress/fixtures/api/insights-results-aggregator/v2/ack/external.rules.rule|ERROR_KEY.json
  cypress/fixtures/api/insights-results-aggregator/v2/cluster/dcb95bbf-8673-4f3a-a63c-12d4a530aa6f/reports-disabled-false.json
  cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail/report.json
  cypress/support/commands.js
  cypress/support/index.js
  cypress/utils/components.js
  cypress/utils/filters.js
  cypress/utils/pagination.js
  cypress/utils/table.js
  package-lock.json
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Breadcrumbs/Breadcrumbs.spec.ct.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/Cluster/index.js
  src/Components/ClusterHeader/ClusterHeader.spec.ct.js
  src/Components/ClusterHeader/index.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersList/index.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Modals/DisableRule.spec.ct.js
  src/Components/Recommendation/Recommendation.js
  src/Components/Recommendation/RuleDetails.js
  src/Components/Recommendation/index.js
  src/Components/RecsList/index.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Components/RuleDetailsLocal/RuleDetails.js
  src/Components/RuleDetailsLocal/RuleRating.js
  src/Components/RuleDetailsLocal/_RuleDetails.scss
  src/Components/RuleDetailsLocal/_RuleRating.scss
  src/Components/RuleDetailsLocal/index.js
  src/Utilities/intlHelper.js
Labels: release/sync-up

#273 Release to prod (prod-stable)
  .github/dependabot.yml
  .stylelintrc.json
  ARCHITECTURE.md
  CHANGELOG.md
  cypress/fixtures/Cluster/report.json
  cypress/fixtures/ClusterRules/data.json
  cypress/fixtures/api/insights-results-aggregator/v2/ack/external.rules.rule|ERROR_KEY.json
  cypress/fixtures/api/insights-results-aggregator/v2/cluster/dcb95bbf-8673-4f3a-a63c-12d4a530aa6f/reports-disabled-false.json
  cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail/report.json
  cypress/support/commands.js
  cypress/support/index.js
  cypress/utils/components.js
  cypress/utils/filters.js
  cypress/utils/pagination.js
  cypress/utils/table.js
  package-lock.json
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Breadcrumbs/Breadcrumbs.spec.ct.js
  src/Components/Cluster/Cluster.spec.ct.js
  src/Components/Cluster/index.js
  src/Components/ClusterHeader/ClusterHeader.spec.ct.js
  src/Components/ClusterHeader/index.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersList/index.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Modals/DisableRule.spec.ct.js
  src/Components/Recommendation/Recommendation.js
  src/Components/Recommendation/RuleDetails.js
  src/Components/Recommendation/index.js
  src/Components/RecsList/index.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Components/RuleDetailsLocal/RuleDetails.js
  src/Components/RuleDetailsLocal/RuleRating.js
  src/Components/RuleDetailsLocal/_RuleDetails.scss
  src/Components/RuleDetailsLocal/_RuleRating.scss
  src/Components/RuleDetailsLocal/index.js
  src/Utilities/intlHelper.js
Labels: release/sync-up

#272 Render cluster version in the affected clusters table
  compiled-lang/en.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
  package-lock.json
  package.json
  src/AppConstants.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/Common/Tables.js
  src/Components/RecsListTable/RecsListTable.js
  src/Messages.js
  src/Services/Filters.js
Labels: enhancement

#265 Improve filtering tests
  cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
  cypress/utils/filters.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#282 Display cluster version in the clusters list table
  compiled-lang/en.json
  cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
  cypress/utils/filters.js
  src/AppConstants.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Common/Tables.js
  src/Messages.js
  src/Services/Filters.js
Labels: enhancement

#279 fix(App): babel transformation for the react-core modules
  babel.config.js
  config/dev.webpack.config.js
  package-lock.json
  package.json
  src/App.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/Breadcrumbs/index.js
  src/Components/ClusterHeader/ClusterHeader.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/Labels/CategoryLabel.js
  src/Components/Labels/RuleLabels.js
  src/Components/Loading/Loading.js
  src/Components/MessageState/EmptyStates.js
  src/Components/MessageState/MessageState.js
  src/Components/Modals/DisableRule.js
  src/Components/Modals/ViewHostAcks.js
  src/Components/Recommendation/Recommendation.js
  src/Components/RecsListTable/RecsListTable.js
  src/Routes.js
  src/Utilities/ErrorBoundary.js
Labels: enhancement

#288 Change data tests to use expect assertion
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
Labels: tests

#289 Use filtersConf approach in Affected clusters table
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
Labels: tests

#297 Deploy to production (prod-stable)
  CHANGELOG.md
  babel.config.js
  compiled-lang/en.json
  config/dev.webpack.config.js
  cypress/fixtures/api/insights-results-aggregator/v2/clusters.json
  cypress/fixtures/api/insights-results-aggregator/v2/rule/external.rules.rule|ERROR_KEY/clusters_detail.json
  cypress/utils/filters.js
  package-lock.json
  package.json
  src/App.js
  src/AppConstants.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
  src/Components/AffectedClustersTable/AffectedClustersTable.spec.ct.js
  src/Components/Breadcrumbs/index.js
  src/Components/ClusterHeader/ClusterHeader.js
  src/Components/ClusterRules/ClusterRules.js
  src/Components/ClusterRules/ClusterRules.spec.ct.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Components/ClustersListTable/ClustersListTable.spec.ct.js
  src/Components/Common/Tables.js
  src/Components/Labels/CategoryLabel.js
  src/Components/Labels/RuleLabels.js
  src/Components/Loading/Loading.js
  src/Components/MessageState/EmptyStates.js
  src/Components/MessageState/MessageState.js
  src/Components/Modals/DisableRule.js
  src/Components/Modals/ViewHostAcks.js
  src/Components/Recommendation/Recommendation.js
  src/Components/RecsListTable/RecsListTable.js
  src/Components/RecsListTable/RecsListTable.spec.ct.js
  src/Messages.js
  src/Routes.js
  src/Services/Filters.js
  src/Utilities/ErrorBoundary.js
Labels: on hold, release/sync-up
