Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2024-03, with the labels that each got.

#681 tests: Upgrade Cypress tests to support PF5 and React 18
  .eslintrc.yml
  .travis.yml
  cypress.config.js
  cypress/support/commands.js
  cypress/support/component.js
  cypress/utils/components.js
  cypress/utils/filters.js
  cypress/utils/pagination.js
  cypress/utils/table.js
  cypress/views/filterableTable.js
  package-lock.json
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.cy.js
  src/Components/Breadcrumbs/Breadcrumbs.cy.js
  src/Components/Cluster/Cluster.cy.js
  src/Components/ClusterHeader/ClusterHeader.cy.js
  src/Components/ClusterHeader/ClusterHeader.js
  src/Components/ClusterRules/ClusterRules.cy.js
  src/Components/ClustersListTable/ClustersListTable.cy.js
  src/Components/Modals/DisableRule.cy.js
  src/Components/Modals/ViewHostsAcks.cy.js
  src/Components/Recommendation/Recommendation.cy.js
  src/Components/Recommendation/Recommendation.js
  src/Components/RecsListTable/RecsListTable.cy.js
  src/Components/UpdateRisksTable/UpdateRisksTable.cy.js
  src/Components/WorkloadsListTable/WorkloadsListTable.cy.js
  src/Components/WorkloadsListTable/WorkloadsListTable.js
Labels: bug, tests

#698 Connect real api
  src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js
  src/Components/ObjectsModal/ObjectsModal.js
  src/Components/Workload/Workload.cy.js
  src/Components/Workload/Workload.js
  src/Components/Workload/index.js
  src/Components/WorkloadHeader/index.js
  src/Components/WorkloadRules/WorkloadRules.js
  src/Components/WorkloadsListTable/index.js
Labels: enhancement

#700 fix(RHINENG-5526): More conditional rendering for expanded details and fixing component structure
  src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js
Labels: enhancement

#702 feat(RHINENG-5503): Objects modal cypress tests
  cypress/fixtures/api/insights-results-aggregator/objects.json
  cypress/support/commands.js
  cypress/utils/table.js
  package-lock.json
  package.json
  src/Components/ObjectsModal/ObjectsModal.cy.js
  src/Components/Workload/Workload.cy.js
Labels: tests

#703 fix(RHINENG-5526): empty state for 404 error
  src/Components/WorkloadRules/WorkloadRules.js
Labels: enhancement

#689 feat(rhineng-5496): combined empty state for workloads table
  src/Components/MessageState/EmptyStates.js
  src/Components/WorkloadsListTable/WorkloadsListTable.js
Labels: enhancement

#705 fix(tests): fixing empty states tests
  src/Components/WorkloadsListTable/WorkloadsListTable.cy.js
Labels: tests

#704 fix(rhineng-5526): moving note text into header to align with mocks
  src/Components/ExpandedRulesDetails.js/ExpandedRulesDetails.js
Labels: bug

#707 fix(bug): remove redundant API call
  src/Components/Workload/Workload.cy.js
  src/Components/Workload/Workload.js
  src/Components/WorkloadHeader/index.js
Labels: bug

#708 feat(rhineng-8808): objects filter now refreshed on close
  src/Components/ObjectsModal/ObjectsModal.js
Labels: bug

#714 chore(deps): updating packages in one go
  package-lock.json
  package.json
  src/Components/AffectedClustersTable/AffectedClustersTable.cy.js
  src/Components/AffectedClustersTable/AffectedClustersTable.js
Labels: dependencies

#717 fix(tests): fixed workload details tests after pf update
  src/Components/Workload/Workload.cy.js
Labels: tests

#706 feat(RHINENG-8253): Update risk label in cluster page
  cypress.config.js
  cypress/fixtures/api/insights-results-aggregator/v2/upgrade-risks-prediction.json
  cypress/utils/interceptors.js
  cypress/utils/table.js
  src/Components/ClustersListTable/ClustersListTable.cy.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Services/SmartProxy.js
Labels: enhancement

#720 feat(RHINENG-7049): fec config setup
  .gitignore
  README.md
  babel.config.js
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  fec.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#722 fix(tests): using experimental strategy to detect flaky tests
  cypress.config.js
  package-lock.json
  package.json
Labels: tests
