Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2024-02, with the labels that each got.

#670 fix(rhineng-7889): fixed a filter bug and wrote more tests
  src/Components/Common/Tables.js
  src/Components/WorkloadRules/WorkloadRules.js
  src/Components/WorkloadRules/WorkloadsRules.test.js
  src/Utilities/Workloads.js
Labels: bug

#672 fix(rhineng-8046): objects modal compact table
  src/Components/ObjectsModalTable/ObjectsModalTable.js
Labels: bug

#673 feat(rhineng-7974): severity link with path and filters
  src/Components/ShieldSet.js
  src/Components/WorkloadsListTable/WorkloadsListTable.js
  src/Utilities/Workloads.js
Labels: enhancement

#674 feat(rhineng-8063): expanded row behavior and more mock data variety
  cypress/fixtures/api/insights-results-aggregator/v2/workload/00000001-0001-0001-0001-000000000005-fad82c1f-96db-430f-b3ec-503fb9eeb7bb/info.json
  src/Components/WorkloadRules/WorkloadRules.js
Labels: enhancement

#675 feat(RHINENG-7886): add a beta check for the prod preview release
  src/Routes.js
  src/Utilities/useFeatureFlag.js
Labels: enhancement

#678 fix(chore): reverting semantic release
  package-lock.json
  package.json
Labels: bug

#637 test(OCPADVISOR-130): Workloads table tests
  cypress/utils/table.js
  src/Components/WorkloadsListTable/WorkloadsListTable.cy.js
Labels: tests

#679 fix(bug): fixing shieldset so it would like before r18 update
  src/Components/ShieldSet.js
Labels: bug

#683 fix(tests): breadcrumb rtl tests
  src/Components/Breadcrumbs/Breadcrumb.test.js
  src/Components/Breadcrumbs/index.js
Labels: tests
