Repository RedHatInsights/ocp-advisor-frontend, pull requests merged in 2024-04, with the labels that each got.

#724 fix(RHINENG-9046): updating report details after fec update
  package-lock.json
  package.json
  src/Components/ClusterRules/ClusterRules.js
Labels: dependencies

#726 fix(RHINENG-9193): breadcrumbs and title when names are absent
  src/Components/Workload/Workload.cy.js
  src/Components/Workload/Workload.js
  src/Components/WorkloadHeader/WorkloadHeader.js
Labels: bug

#721 fix(RHINENG-8253): Update risk label condition
  config/overrideChrome.js
  cypress/fixtures/api/insights-results-aggregator/v2/upgrade-risks-prediction.json
  cypress/utils/interceptors.js
  package-lock.json
  package.json
  src/Components/ClustersListTable/ClustersListTable.cy.js
  src/Components/ClustersListTable/ClustersListTable.js
  src/Services/SmartProxy.js
Labels: enhancement

#728 fix(RHINENG-8615): Fix "View ${n} affected clusters" link missing
  package-lock.json
  src/Components/RecsListTable/RecsListTable.cy.js
  src/Components/RecsListTable/RecsListTable.js
Labels: bug

#731 fix(RHINENG-9058): fixed action button alignment
  src/Components/Cluster/Cluster.cy.js
  src/Components/ClusterHeader/ClusterHeader.js
Labels: bug
